models/Duel.php
<?php
/**
 * @property integer $caller
 * @property integer $opponent
 * @property boolean $isChallenge
 * @property boolean $played
 * @property array $competitors
 */
class Duel extends CModel
{
    private $caller;
    private $opponent;
    private $competitors = [];
    private $callerDuelShieldLifeTime = false;

    private $challengeID = 0;
    private $callersClub = '';
    private $callersClubRole = '';
    private $opponentsClub = '';
    private $opponentsClubRole = '';

    public function attributeNames()
    {
        return [];
    }

    public function getOpponent()
    {
        return $this->opponent;
    }

    public function getCaller()
    {
        return $this->caller;
    }

    public function getIsChallenge()
    {
        return $this->challengeID > 0;
    }

    public function getPlayed()
    {
        if (!isset($this->competitors[1])) {
            return false;
        }

        return ($this->competitors[0]->winner | $this->competitors[1]->winner);
    }

    public function getCompetitors()
    {
        return $this->competitors;
    }

    public function setCaller($id)
    {
        $this->caller = $this->getPlayerModel($id);
        $duelShiel = new DuelShield();
        $duelShiel->uid = $id;
        $this->callerDuelShieldLifeTime = $duelShiel->lifeTime;
    }

    public function setOpponent($id)
    {
        $this->opponent = $this->getPlayerModel($id);
        $duelShiel = new DuelShield();
        $duelShiel->uid = $id;
        if ($duelShiel->lifeTime > 0) {
            $this->opponent->activateDuelShield();
        }
    }

    private function getPlayerModel($id)
    {
        if ($id == Yii::app()->player->uid) {
            return Yii::app()->player->model;
        }

        $player = new Player();
        if ($id) {
            $player->setAllAttributes($id);
        }

        return $player;
    }

    public function fetchClubChallengeState()
    {
        $c = $this->caller->in_club;
        $o = $this->opponent->in_club;

        if (!$c || !$o) {
            return false;
        }

        $last = Yii::app()->db->createCommand()
            ->select('*')
            ->from('challenge')
            ->where('(caller=:caller OR caller=:opponent) AND winner=0', [':caller'=>$c, ':opponent'=>$o])
            ->limit(1)
            ->queryRow();

        if ($last['caller']==$c && $last['opponent']==$o || $last['caller']==$o && $last['opponent']==$c) {
            $this->setClubAttributes($last);
        }
    }

    private function setClubAttributes($challenge)
    {
        $created = strtotime($challenge['created']);

        if ($this->isBetweenDates($created + 1800, $created + 3600)) {
            $this->challengeID = (int)$challenge['id'];

            $this->callersClubRole = $challenge['caller'] == $this->caller->in_club ? 'caller' : 'opponent';
            $this->callersClub = $challenge['caller'] == $this->caller->in_club ? $challenge['name_caller'] : $challenge['name_opponent'];

            $this->opponentsClubRole = $challenge['opponent'] == $this->opponent->in_club ? 'opponent' : 'caller';
            $this->opponentsClub = $challenge['opponent'] == $this->opponent->in_club ? $challenge['name_opponent'] : $challenge['name_caller'];
        }
    }

    /**
     * @param integer $start
     * @param integer $end
     */
    private function isBetweenDates($start, $end)
    {
        $now = time();
        return ($now >= $start && $now <= $end);
    }

    public function validateDuel()
    {
        if (!$this->opponent->uid) {
            throw new CFlashException('Az ellenfél nem létezik.');
        }

        if ($this->opponent->uid == $this->caller->uid) {
            throw new CFlashException('Magad ellen nem párbajozhatsz.');
        }

        if ($this->callerDuelShieldLifeTime > 0) {
            throw new CFlashException('Be van kapcsolva a párbaj-pajzsod, így nem hívhatsz párbajra másokat.');
        }

        Yii::trace('check: caller - energyRequiredForDuel');
        if ($this->caller->energy < $this->caller->energyRequiredForDuel) {
            throw new CFlashException('Ahhoz, hogy párbajozhass, legalább ' . $this->caller->energyRequiredForDuel . ' energiára van szükséged.');
        }

        if ($this->opponent->level < Yii::app()->params['duelLevelRequirement']) {
            throw new CFlashException('Az ellenfél még nem párbajozhat, mivel nem érte el a szükséges ' . Yii::app()->params['duelLevelRequirement'] . '. szintet.');
        }

        $this->validateNonChallengeGame();

        return true;
    }

    private function validateNonChallengeGame()
    {
        if ($this->isChallenge) {
            return true;
        }

        if ($this->opponent->level < Yii::app()->player->model->level - Yii::app()->params['duelWeakerOpponentLevelDiff']) {
            if (!$this->isRevenge()) {
                throw new CFlashException('Az ellenfél gyengébb nálad a megengedettnél (' . Yii::app()->params['duelWeakerOpponentLevelDiff'] . ' szint).');
            }
        }

        Yii::trace('check: opponent - energyRequiredForDuel');
        if ($this->opponent->energy < $this->opponent->energyRequiredForDuel) {
            throw new CFlashException('Az ellenfélnek nincs elég energiája a párbajhoz.');
        }

        if ($this->duelsInLastHour() >= Yii::app()->params['duelMaxCallPerHour']) {
            throw new CFlashException('Ugyanazt a játékost max. ' . Yii::app()->params['duelMaxCallPerHour'] . 'x hívhatod párbajra egy órán keresztül. Kérlek válassz másik ellenfelet.');
        }

        return true;
    }

    private function createCompetitors()
    {
        if ($this->isChallenge) {
            $c = new ClubCompetitor();
            $o = new ClubCompetitor();
        } else {
            $c = new Competitor();
            $o = new Competitor();
        }

        $c->uid = $this->caller->uid;
        $o->uid = $this->opponent->uid;

        $c->skill = $this->caller->skill_extended;
        $o->skill = $this->opponent->skill_extended;

        $sumSkill = $c->skill + $o->skill;
        $c->chance = round($c->skill / ($sumSkill / 100));
        $c->chance = min($c->chance, 99); //max 99
        $o->chance = 100 - $c->chance;

        $c->energy = $this->caller->energyRequiredForDuel;
        $o->energy = min($this->opponent->energyRequiredForDuel, $this->opponent->energy);

        $avgEnergy = round(($c->energy + $o->energy) / 2);
        $c->avgEnergy = $avgEnergy;
        $o->avgEnergy = $avgEnergy;

        $c->dollar = round($this->caller->dollar / 10);
        $o->dollar = round($this->opponent->dollar / 10);

        $c->club = $this->callersClub;
        $o->club = $this->opponentsClub;

        $c->opponent = [
            'chance'=>$o->chance,
            'dollar'=>$o->dollar,
            'energy'=>$o->energy,
            ];
        $o->opponent = [
            'chance'=>$c->chance,
            'dollar'=>$c->dollar,
            'energy'=>$c->energy,
            'uid'=>$c->uid, //only for wall messages
            'user'=>$this->caller->user //only for wall messages
            ];

        $c->isCaller = true;

        $this->competitors[] = $c;
        $this->competitors[] = $o;
    }

    public function play()
    {
        $this->createCompetitors();

        //play
        $rnd = rand(1, 100);
        $winnersId = 1; //opponent
        if ($rnd <= $this->competitors[0]->chance) {
            $winnersId = 0; //caller
        }

        $this->competitors[0]->play(0==$winnersId);
        $this->competitors[1]->play(1==$winnersId);

        $this->log();
        $this->competitors[0]->finish($this->caller);
        $this->competitors[1]->finish($this->opponent);

        if ($this->isChallenge) {
            $this->updateWinnerClub();
        }
    }

    /**
     * @param integer $duelId
     */
    public function replay($duelId)
    {
        //fetch duel data
        $duel = Yii::app()->db->createCommand()
            ->select('*')
            ->from('duel')
            ->where('id = :id', [':id'=>$duelId])
            ->queryRow();
        if (!$duel['id']) {
            throw new CFlashException('A lekért párbaj nem található.');
        }

        if (Yii::app()->player->uid != $duel['caller'] && Yii::app()->player->uid != $duel['opponent']) {
            throw new CFlashException('A lekért párbajt mások játszották.');
        }

        $this->challengeID = (int)$duel['challenge_id'];

        $this->setCaller($duel['caller']);
        $this->setOpponent($duel['opponent']);

        if ($this->isChallenge) {
            $c = new ClubCompetitor();
            $o = new ClubCompetitor();
        } else {
            $c = new Competitor();
            $o = new Competitor();
        }

        $c->uid = $duel['caller'];
        $c->isCaller = true;
        $c->fetchFromLog($duelId);
        $this->competitors[] = $c;

        $o->uid = $duel['opponent'];
        $o->fetchFromLog($duelId);
        $this->competitors[] = $o;
    }

    private function log()
    {
        //insert the duel data
        Yii::app()->db->createCommand()
            ->insert(
                'duel',
                [
                'winner'=>$this->competitors[0]->winner ? 'caller' : 'opponent',
                'caller'=>$this->caller->uid,
                'opponent'=>$this->opponent->uid,
                'challenge_id'=>$this->challengeID
                ]
            );

        $duelId = Yii::app()->db->getLastInsertID();
        $this->competitors[0]->duelId = $duelId;
        $this->competitors[1]->duelId = $duelId;
    }

    private function updateWinnerClub()
    {
        $tag = $this->callersClubRole;
        $winner = $this->competitors[0];
        if ($this->competitors[1]->winner) {
            $tag = $this->opponentsClubRole;
            $winner = $this->competitors[1];
        }

controllers/DuelController.php
<?php
class DuelController extends GameController
{
    protected function beforeAction($action)
    {
        parent::beforeAction($action);

        if (Yii::app()->player->model->level < Yii::app()->params['duelLevelRequirement']) {
            $this->render('lowlevel', [
                'levelRequirement' => Yii::app()->params['duelLevelRequirement']
            ]);
            return false;
        }
        return true;
    }


    public function actionIndex($page = 0)
    {
        $duelList = new DuelList();
        $duelList->page = $page;
        $duelList->fetchOpponents();

        $this->render('index', [
            'list'=>$duelList->opponents,
            'pagination' => $duelList->pagination,
            'count' => $duelList->count,
            'page_size' => Yii::app()->params['listPerPage'],
            'page'=>$page,
            ]);
    }

    public function actionCommon()
    {
        $duelList = new DuelList();
        $duelList->fetchCommonRivals();

        $this->render('commonrivals', [
            'list'=>$duelList->opponents,
            ]);
    }

    public function actionHistory()
    {
        $duelList = new DuelList();
        $duelList->fetchLastRivals();

        $this->render('history', [
            'list'=>$duelList->opponents,
            ]);
    }

    public function actionGo($opponentId = 0)
    {
        $duel = new Duel();
        $duel->caller = Yii::app()->player->uid;
        $duel->opponent = $opponentId;
        $duel->fetchClubChallengeState();

        try {
            if ($duel->validateDuel()) {
                $duel->play();
            }
        } catch (CFlashException $e) {
            Yii::app()->user->setFlash('error', $e->getMessage());
        }

        $this->render('go', [
            'duel'=>$duel,
            ]);
    }

    public function actionReplay($id)
    {
        $duel = new Duel;
        try {
            $duel->replay((int)$id);
        } catch (CFlashException $e) {
            Yii::app()->user->setFlash('error', $e->getMessage());
            $this->redirect('/duel');
        }

        $this->render('replay', [
            'duel'=>$duel,
            ]);
    }
}

views/duel/_parameters.php
<ul class="missions" data-role="listview" data-inset="true">
    <li class="c" data-role="list-divider"><?= CHtml::link($user, ['/player/profile', 'uid'=>$p->uid]); ?></li>
    <?php if($isChallenge): ?><li><p><?= $p->club ?></p></li><?php endif; ?>
    <li>
        <?php if ($p->winner): ?><p class="success">győztes</p><?php else: ?><p class="error">vesztes</p><?php endif; ?>
        <p><?= $p->skill; ?> SzP<br/>
        <?= $p->chance; ?>% nyerési esély</p>

        <?php if (!$p->energy && !$p->winner): ?>
            <p class="error">Nincs energiája, ezért pénzt nem veszíthet.</p>
        <?php endif; ?>
    </li>


    <?php if ($p->awardXp || $p->awardDollar || $p->awardPoints): ?>
        <li>
            <h5>jutalmak</h5>
            <p>
            <?php 
                echo $p->awardXp ? $p->awardXp . 'tp<br/>' : '';
                if (!$isChallenge) {
                    echo $p->awardDollar ? $p->awardDollar . '$<br/>' : '';
                    echo $p->awardPoints ? $p->awardPoints . ' pont a ranglistán' : '';
                }
            ?>
            </p>
        </li>

        <?php if ($p->winner && $isChallenge): ?>
        <li>
            <h5>jutalmak a klubnak</h5>
            <p>
            +1 nyeremény<br/>
            <?php 
                echo $p->awardDollar ? $p->awardDollar . '$ zsákmány<br/>' : '';
                echo $p->awardPoints ? $p->awardPoints . ' pont' : '';
            ?>
            </p>
        </li>
        <?php endif; ?>
    <?php endif; ?>

    <li>
        <h5>követelmények</h5>
        <p>
        <?php echo $p->reqEnergy ? $p->reqEnergy . ' energia<br/>' : '' ?>
        <?php echo $p->reqDollar ? $p->reqDollar . '$' : '' ?>
        </p>
    </li>
</ul>

views/duel/_player.php
<li>
    <?php $paramPage = $page ? ['page'=>$page] : []; ?>
    <?php if (!$item['disabled']): ?>
    <form class="right" action="<?= $this->createUrl('go', $paramPage) ?>" method="get">
        <button name="opponentId" value="<?= $item['uid'] ?>" data-inline="true" data-mini="true">kihívás</button>
    </form>
    <?php elseif ($item['disabled'] == 1): ?>
    <form class="right" action="#" method="get">
        <button name="opponentID" value="0" disabled="disabled" data-inline="true" data-mini="true">túl fáradt</button>
    </form>
    <?php elseif ($item['disabled'] == 2): ?>
    <form class="right" action="#" method="get">
        <button name="opponentID" value="0" disabled="disabled" data-inline="true" data-mini="true">túl gyenge</button>
    </form>
    <?php endif; ?>

    <h3><?= CHtml::link($item['user'], ['player/profile', 'uid'=>$item['uid']]); ?> <?= $item['clubName']; ?></h3>
    <p>
        <?= $item['level'] ?>. szint, 
        <?= $item['energy'] ?> energia,
        <?= $item['prize'] ?>$ tét.
        <?php if (isset($item['cnt'])): ?><strong><?= $item['cnt'] ?>x párbajoztál vele</strong><?php endif; ?>
        <?php if (isset($item['created'])): ?>
            <br/><strong>legutóbb: <?= $item['created'] ?></strong>
            <?= CHtml::link('megnézem', ['duel/replay', 'id'=>$item['id']]); ?>
        <?php endif; ?>
    </p>
</li>

views/duel/commonrivals.php
<?php
$this->pageTitle='Pecapárbaj';
$this->renderPartial('/duel/nav');
?>

<ul class="controls-in-right" data-role="listview" data-inset="true">
    <li data-role="list-divider">Gyakori ellenfelek</li>
    <?php
        if (count($list)) {
            foreach($list as $item) {
                Yii::app()->controller->renderPartial('_player', ['item' => $item, 'page' => 0]);
            }
        } else {
            echo '<li>Még nem párbajoztál senkivel sem.</li>';
        }
    ?>
</ul>

<?php $this->widget('HelpWidget', ['topic'=>'duel']); ?>

views/duel/go.php
<?php
$this->pageTitle='Pecapárbaj';
$this->renderPartial('/duel/nav', ['title'=>'A párbaj eredménye', 'opponent'=>$duel->opponent->uid]);
?>

<?php if ($duel->played): ?>
    <div class="duel-grid ui-grid-a">
        <div class="ui-block-a">
            <?php $this->renderPartial('_parameters', [
                'user'=>$duel->caller->user, 
                'p'=>$duel->competitors[0], 
                'isChallenge'=>$duel->isChallenge,
                ]
            ); ?> 
        </div>
        <div class="ui-block-b">
            <?php $this->renderPartial('_parameters', [
                'user'=>$duel->opponent->user, 
                'p'=>$duel->competitors[1], 
                'isChallenge'=>$duel->isChallenge,
                ]
            ); ?> 
        </div>
    </div><!-- /grid-a -->
<?php else: ?>
    <p>Próbálkozz később, esetleg másik ellenféllel.</p>
<?php endif; ?>

<?php $this->widget('HelpWidget', ['topic'=>'duel']); ?>

views/duel/history.php
<?php
$this->pageTitle='Pecapárbaj';
$this->renderPartial('/duel/nav');
?>

<ul class="controls-in-right" data-role="listview" data-inset="true">
    <li data-role="list-divider">Legutóbbi ellenfelek</li>
    <?php
        if (count($list)) {
            foreach($list as $item) {
                Yii::app()->controller->renderPartial('_player', ['item' => $item, 'page' => 0]);
            }
        } else {
            echo '<li>Még nem párbajoztál senkivel sem.</li>';
        }
    ?>
</ul>

<?php $this->widget('HelpWidget', ['topic'=>'duel']); ?>

views/duel/index.php
<?php
$this->pageTitle='Pecapárbaj';
$this->renderPartial('/duel/nav');
?>

<ul class="controls-in-right" data-role="listview" data-inset="true">
    <li data-role="list-divider">Ők versenyeznének</li>
    <?php
        if (count($list)) {
        foreach($list as $item) {
            Yii::app()->controller->renderPartial('_player', ['item' => $item, 'page' => $page]);
        }
        } else {
            echo '<li>Jelenleg nem találtunk megfelelő ellenfelet.</li>';
        }
    ?>
</ul>

<div class="center-wrapper">
<?php 
$this->widget('JqmLinkPager', array(
    'currentPage'=>$pagination->getCurrentPage(),
    'itemCount'=>$count,
    'pageSize'=>$page_size,
));
?>
</div>

<?php $this->widget('HelpWidget', ['topic'=>'duel']); ?>

views/duel/lowlevel.php
<?php
$this->pageTitle='Pecapárbaj';
$this->renderPartial('/duel/nav', ['title'=>'Pecapárbaj']);
?>

<p>Még nem vagy elég tapasztalt ahhoz, hogy párbajozz.</p>
<p>Ne aggódj, amint eléred a szükséges <?= $levelRequirement; ?>. szintet, összemérheted tudásodat a többi horgásszal és akár a pénzüket is elnyerheted.</p>

views/duel/nav.php
<div class="nav">
    <div class="right">
        <?php if (isset($opponent)): ?>
            <a href="<?= $this->createUrl('duel/go', ['opponentId'=>$opponent]); ?>" data-role="button" data-inline="true" data-mini="true">újra</a>
        <?php endif; ?>

        <?php if (isset($replay)): ?>
            <a href="<?= $this->createUrl('duel/go', ['opponentId'=>$replay['uid']]); ?>" data-role="button" data-inline="true" data-mini="true"><?= $replay['title'] ?></a>
        <?php endif; ?>
        
        <a href="#popupMenu" data-rel="popup" data-role="button" data-inline="true" data-mini="true">Szűrők</a>
        <div data-role="popup" id="popupMenu">
            <ul data-role="listview" data-inset="true" style="min-width:210px;">
                <li data-role="divider">Mire vagy kíváncsi?</li>
                <li><?= CHtml::link('Jelentkezők', ['/duel']); ?></li>
                <li><?= CHtml::link('Gyakori ellenfelek', ['/duel/common']); ?></li>
                <li><?= CHtml::link('Legutóbbi ellenfelek', ['/duel/history']); ?></li>
            </ul>
        </div>    
    </div>
    
    <h1><?php echo  isset($title) ? $title : 'Pecapárbaj'; ?></h1>
</div>

views/duel/replay.php
<?php
$this->pageTitle='Pecapárbaj: ismétlés';

$this->renderPartial('/duel/nav', [
    'title'=>'A párbaj eredménye', 
    'replay'=>[
        'uid'=>$duel->caller->uid == Yii::app()->player->uid ? $duel->opponent->uid : $duel->caller->uid,
        'title'=>$duel->caller->uid == Yii::app()->player->uid ? 'újra' : 'visszavágó',
        ]
        ]);
?>

<div class="duel-grid ui-grid-a">
    <div class="ui-block-a">
        <?php $this->renderPartial('_parameters', [
            'user'=>$duel->caller->user, 
            'p'=>$duel->competitors[0], 
            'isChallenge'=>$duel->isChallenge,
            ]
        ); ?> 
    </div>
    <div class="ui-block-b">
        <?php $this->renderPartial('_parameters', [
            'user'=>$duel->opponent->user, 
            'p'=>$duel->competitors[1], 
            'isChallenge'=>$duel->isChallenge,
            ]
        ); ?> 
    </div>
</div><!-- /grid-a -->