models/Leaderboard.php
<?php
/**
 * @property integer $uid
 * @property integer $inClub
 * @property array $items
 * @property string $boardType
 * @property string $range
 * @property string $title
 * @property string $playerRankDescription
 * @property string $clubRankDescription
 */
class Leaderboard extends CModel
{
    const BOARD_RANGE = 5;
    const TYPE_PLAYER = 'board_p';
    const TYPE_CLUB = 'board_c';

    const RANGE_ACTUAL = 'actual';
    const RANGE_PREVIOUS = 'prev';
    const RANGE_LAST_SIX = 'last';

    private $uid;
    private $inClub;
    private $items = [];
    private $key = '';
    private $boardType;
    private $range;

    public function attributeNames()
    {
        return [];
    }

    public function getUid()
    {
        return $this->uid;
    }

    public function getInClub()
    {
        return $this->inClub;
    }

    public function getItems()
    {
        return $this->items;
    }

    public function getBoardType()
    {
        return $this->boardType;
    }

    public function getRange()
    {
        return $this->range;
    }

    public function getTitle()
    {
        $titles = [
            self::TYPE_PLAYER => [
            self::RANGE_ACTUAL => 'Aktuális hónap legjobb játékosai',
            self::RANGE_PREVIOUS => 'Előző hónap legjobb játékosai',
            self::RANGE_LAST_SIX => 'Utolsó 6 hónap legjobb játékosai',
            ],
            self::TYPE_CLUB => [
            self::RANGE_ACTUAL => 'Aktuális hónap legjobb klubjai',
            self::RANGE_PREVIOUS => 'Előző hónap legjobb klubjai',
            self::RANGE_LAST_SIX => 'Utolsó 6 hónap legjobb klubjai',
            ]
            ];
        return $titles[$this->boardType][$this->range];
    }

    public function getPlayerRankDescription()
    {
        $redis = Yii::app()->redis->getClient();

        $total = $redis->zCard($this->key);
        $rank  = $redis->zRevRank($this->key, $this->uid) + 1;

        if ($rank == 1) {
            return 'Te vagy a király!';
        } else {
            $percent = round((1 - ($rank / $total)) * 100, 1);
            if (!$percent) {
                return 'Több párbajgyőzelemre van szükséged.';
            }

            return 'Jobb vagy, mint a játékosok ' . $percent . '%-a!';
        }
    }

    public function getClubRankDescription()
    {
        $redis = Yii::app()->redis->getClient();

        $total = $redis->zCard($this->key);
        $rank  = $redis->zRevRank($this->key, $this->inClub) + 1;

        if ($rank == 1) {
            return 'A te klubod a király!';
        } else {
            $percent = round((1 - ($rank / $total)) * 100, 1);
            if (!$percent) {
                return 'Több versenygyőzelemre van szükségetek.';
            }

            return 'Jobb a klubod, mint a többi klub ' . $percent . '%-a!';
        }
    }

    public function setBoardType ($type)
    {
        $this->boardType = $type;
    }

    public function setRange ($range)
    {
        $d = new DateTime();

        //create key from date/intersect
        switch ($range) {
            case self::RANGE_LAST_SIX:
                $this->key = $this->boardType . ':6month';
                //create intersect

                $history = [];
                $history[] = $this->boardType . ':' . $d->format('Ym');

                for ($i=0; $i<6; $i++) {
                    $d->modify('first day of previous month');
                    $history[] = $this->boardType . ':' . $d->format('Ym');
                }

                $redis = Yii::app()->redis->getClient();
                $redis->zUnionStore($this->key, $history);

                break;
            case self::RANGE_PREVIOUS:
                $d->modify('first day of previous month');
                $this->key = $this->boardType . ':' . $d->format('Ym');
                break;
            default:
                $range = self::RANGE_ACTUAL;
                $this->key = $this->boardType . ':' . $d->format('Ym');
        }
        $this->range = $range;
    }

    public function setUid($uid)
    {
        $this->uid = (int)$uid;
    }

    public function setInClub($id)
    {
        $this->inClub = (int)$id;
    }

    public function fetchList()
    {
        if ($this->boardType == self::TYPE_PLAYER) {
            $class = 'Player';
        } else {
            $class = 'Club';
        }

        $redis = Yii::app()->redis->getClient();

        $myRank = $redis->zRevRank($this->key, $this->inClub);

        $range = self::BOARD_RANGE;
        $min = $myRank - $range > 0 ? $myRank - $range : 0;
        $max = $myRank + $range + ($range-$myRank+$min);

        $item = new $class;
        $i = $min+1;
        foreach ($redis->zRevRange($this->key, $min, $max, true) as $id => $score) {
            $item->subjectId = $id;

            $this->items[$i] = [
                'id'=>$id,
                'name'=>$item->getSubjectName(),
                'score'=>$score,
                ];
            $i++;
        }
    }

    public function getRankDescription()
    {
        if ($this->boardType == self::TYPE_CLUB) {
            $ret = $this->getClubRankDescription();
        } else {
            $ret = $this->getPlayerRankDescription();
        }
        return $ret;
    }
}

controllers/LeaderboardController.php
<?php
class LeaderboardController extends GameController
{
    public function actionIndex($range = '')
    {
        $this->makeBoard(Leaderboard::TYPE_PLAYER, $range);
    }

    public function actionClub($range = '')
    {
        $this->makeBoard(Leaderboard::TYPE_CLUB, $range);
    }

    /**
     * @param string $range
     */
    private function makeBoard($type, $range)
    {
        $board = new Leaderboard;
        $board->uid = Yii::app()->player->model->uid;
        $board->inClub = Yii::app()->player->model->in_club;
        $board->boardType = $type;

        switch ($range) {
            case 'prev':
                $board->setRange(Leaderboard::RANGE_PREVIOUS);
                break;
            case 'last':
                $board->setRange(Leaderboard::RANGE_LAST_SIX);
                break;
            default:
                $board->setRange(Leaderboard::RANGE_ACTUAL);
                break;
        }
        $board->fetchList();

        $this->render('index', [
            'board'=>$board,
            ]);
    }
}

views/leaderboard/_list.php
<ul class="board" data-role="listview" data-inset="true">
    <li data-role="list-divider"><?= $board->title; ?></li>
    <?php foreach($board->items as $rank => $item): ?>
    <li>
    <p><strong><?= $rank ?>. </strong> 
    <?php
    if ($board->boardType==Leaderboard::TYPE_CLUB) {
        if ($item['name']) {
            echo CHtml::link($item['name'], ['club/details', 'id'=>$item['id']]);
        } else {
            echo 'Törölt klub';
        }
    } else {
        if ($item['name']) {
            echo CHtml::link($item['name'], ['player/profile', 'uid'=>$item['id']]);
        } else {
            echo 'Törölt felhasználó';
        }
    }
    ?>
    </p>
    <?php if ($board->uid == $item['id'] || $board->inClub == $item['id']): ?>
    <p class="success"><?= $board->rankDescription; ?></p>
    <?php endif; ?>
    <p class="ui-li-aside muted"><strong><?= $item['score'] ?> pont</strong></p>
    </li>
    <?php endforeach; ?>
</ul>

views/leaderboard/index.php
<?php
$this->pageTitle = 'Ranglista';
?>

<div class="nav">
    <h1>Ranglista</h1>
</div>

<div class="grid-board ui-grid-a ui-responsive">
    <div class="block ui-block-a">
        <?php $this->renderPartial('_list', ['board'=>$board]); ?>
    </div>
    <div class="block ui-block-b">

    <div data-role="collapsible-set" data-content-theme="d" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" class="board-menu">
        <div data-role="collapsible" data-inset="false"<?= $board->boardType == 'board_p'?' data-collapsed="false"':'';?>>
            <h2>Játékosok</h2>
            <ul data-role="listview">
                <li><?= CHtml::link('aktuális hónap', ['index'], ['class'=>$board->boardType == 'board_p' & $board->range == 'actual' ? 'ui-disabled' : '']); ?></li>
                <li><?= CHtml::link('előző hónap', ['index', 'range'=>'prev'], ['class'=>$board->boardType == 'board_p' & $board->range == 'prev'?'ui-disabled':'']); ?></li>
                <li><?= CHtml::link('összesített: utolsó 6 hónap', ['index', 'range'=>'last'], ['class'=>$board->boardType == 'board_p' & $board->range == 'last'?'ui-disabled':'']); ?></li>
            </ul>
        </div><!-- /collapsible -->
        <div data-role="collapsible" data-inset="false"<?= $board->boardType == 'board_c'?' data-collapsed="false"':'';?>>
            <h2>Klubok</h2>
            <ul data-role="listview">
                <li><?= CHtml::link('aktuális hónap', ['club'], ['class'=>$board->boardType == 'board_c' & $board->range == 'actual' ? 'ui-disabled' : '']); ?></li>
                <li><?= CHtml::link('előző hónap', ['club', 'range'=>'prev'], ['class'=>$board->boardType == 'board_c' & $board->range == 'prev'?'ui-disabled':'']); ?></li>
                <li><?= CHtml::link('összesített: utolsó 6 hónap', ['club', 'range'=>'last'], ['class'=>$board->boardType == 'board_c' & $board->range == 'last'?'ui-disabled':'']); ?></li>
            </ul>
        </div><!-- /collapsible -->
    </div> 

    </div>
</div><!-- /grid-a -->