models/Player.php
<?php
/**
 * @property integer $uid
 * @property string $user
 * @property string $registered
 * @property integer $level
 * @property integer $status_points
 * @property integer $energy
 * @property integer $energy_max
 * @property integer $energy_missing
 * @property integer $energyRequiredForDuel
 * @property integer $skill
 * @property integer $strength
 * @property integer $dollar
 * @property integer $gold
 * @property integer $xp_all
 * @property integer $xp_delta
 * @property integer $xp_remaining
 * @property integer $last_location
 * @property integer $owned_items
 * @property integer $owned_baits
 * @property string $found_setitem_time
 * @property integer $found_setitem_xp
 * @property integer $tutorial_mission
 * @property integer $in_club
 * @property integer $level_percent
 * @property integer $refillPerInterval
 * @property integer $energyRefillPerInterval
 * @property integer $remainingTimeToRefill
 * @property integer $justAdvanced
 * @property integer $freeSlots
 * @property boolean $black_market
 * @property integer $skill_extended
 * @property string $clubName
 */
class Player extends CModel implements ISubject
{
    const ENERGY_REFILL_INTERVAL = 300; //5min

    private $uid;
    private $user;
    private $registered;
    private $xp_all;
    private $xp_delta;
    private $xp_recommended;
    private $level;
    private $status_points;
    private $energy_max;
    private $energy_incr_at;
    private $energy;
    private $skill;
    private $skill_extended;
    private $strength;
    private $dollar;
    private $gold;
    private $last_location;
    private $owned_items;
    private $owned_baits;
    private $found_setitem_time;
    private $found_setitem_xp;
    private $duel_points;
    private $tutorial_mission;
    private $in_club;
    private $black_market;

    private $justAdvanced;

    public function attributeNames()
    {
        return [];
    }

    public function getUid()
    {
        return (int)$this->uid;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function getRegistered()
    {
        return $this->registered;
    }

    public function getLevel()
    {
        return (int)$this->level;
    }

    public function getStatus_points()
    {
        return $this->itsMe() ? (int)$this->status_points : 0;
    }

    public function getEnergy()
    {
        return (int)$this->energy;
    }

    public function getEnergy_max()
    {
        return (int)$this->energy_max;
    }

    public function getEnergy_missing()
    {
        return $this->energy_max - $this->energy;
    }

    public function getEnergyRequiredForDuel()
    {
        return round($this->energy_max / 10);
    }

    public function getSkill()
    {
        return (int)$this->skill;
    }

    public function getStrength()
    {
        return (int)$this->strength;
    }

    public function getDollar()
    {
        return (int)$this->dollar;
    }

    public function getGold()
    {
        return (int)$this->gold;
    }

    public function getXp_all()
    {
        return (int)$this->xp_all;
    }

    public function getXp_delta()
    {
        return (int)$this->xp_delta;
    }

    public function getXp_remaining()
    {
        return (int)$this->xp_recommended - (int)$this->xp_delta;
    }

    public function getLast_location()
    {
        return (int)$this->last_location;
    }

    public function getOwned_items()
    {
        return (int)$this->owned_items;
    }

    public function getOwned_baits()
    {
        return (int)$this->owned_baits;
    }

    public function getFound_setitem_time()
    {
        return $this->found_setitem_time > $this->registered ? $this->found_setitem_time : $this->registered;
    }

    public function getFound_setitem_xp()
    {
        return (int)$this->found_setitem_xp;
    }

    public function getTutorial_mission()
    {
        return (int)$this->tutorial_mission;
    }

    public function getIn_club()
    {
        return (int)$this->in_club;
    }

    public function getLevel_percent()
    {
        if (!$this->xp_recommended) {
            return 0;
        }
        $percent = (int)$this->xp_delta / ((int)$this->xp_recommended / 100);

        if ($percent < 0) {
            $percent = 0;
        }
        if ($percent > 100) {
            $percent = 100;
        }
        return $percent;
    }

    public function getRefillPerInterval()
    {
        return round($this->energy_max / 10);
    }

    public function getEnergyRefillInterval()
    {
        return self::ENERGY_REFILL_INTERVAL;
    }

    public function getRemainingTimeToRefill()
    {
        $last = strtotime($this->energy_incr_at);
        if ($last < 0) {
            $last = 0;
        }

        $remaining = self::ENERGY_REFILL_INTERVAL - (time() - $last);
        if ($remaining < 0) {
            $remaining = 0;
        }

        return $remaining;
    }

    public function getJustAdvanced()
    {
        return (int)$this->justAdvanced;
    }

    public function getFreeSlots()
    {
        return $this->strength - ($this->owned_items + $this->owned_baits);
    }

    public function getBlack_market()
    {
        return (bool)(strtotime($this->black_market) >= time());
    }

    public function itsMe()
    {
        return $this->uid == @$_SESSION['uid'];
    }

    public function getSkill_extended()
    {
        return $this->skill_extended>0 ? $this->skill_extended : 1;
    }

    public function getClubName()
    {
        if (!$this->in_club) {
            return false;
        }

        $club = new Club;
        $club->id = $this->in_club;
        $club->fetchName();
        return $club->name;
    }

    public function setSubjectId($id)
    {
        $this->uid = (int)$id;
    }

    public function setOwned_baits($baits)
    {
        $this->owned_baits = (int)$baits;
    }

    public function setOwned_items($items)
    {
        $this->owned_items = (int)$items;
    }

    public function activateDuelShield()
    {
        Yii::trace($this->uid . ': activate duelShield.');
        $this->energy = 0;
    }

    public function fetchUser()
    {
        $user = Yii::app()->db->cache(86400)->createCommand()
            ->select('user')
            ->from('main')
            ->where('uid=:uid', [':uid'=>$this->uid])
            ->queryScalar();
        if (!$user) {
            $user = '???';
        }
        $this->user = $user;
    }

    public function getSubjectName()
    {
        $name = Yii::app()->db->cache(86400)->createCommand()
            ->select('user')
            ->from('main')
            ->where('uid=:uid', [':uid'=>$this->uid])
            ->queryScalar();
        if (!$name) {
            $name = '???';
        }
        return $name;
    }

    public function setAllAttributes($uid = 0)
    {
        $this->setSubjectId( $uid ? $uid : @$_SESSION['uid'] );

        if (!$this->uid) {
            return false;
        }

        //read all from db
        $res = Yii::app()->db->createCommand()
            ->select('*')
            ->from('main')
            ->where('uid=:uid', [':uid'=>$this->uid])
            ->queryRow();

        if (!is_array($res)) {
            $this->uid = 0;
            return false;
        }

        foreach ($res as $k => $v) {
            $this->$k = $v;
        }
    }

    public function rest()
    {
        $refillable = $this->energy_max - $this->energy;
        if (!$refillable) {
            return false; //don't need to rest
        }

        $now = time();
        $last = strtotime($this->energy_incr_at);
        if ($last<0) {
            $last = 0;
        }

        $interval = $now - $last;
        if ($interval < self::ENERGY_REFILL_INTERVAL) {
            return false;
        }

        $refillMultiplier = floor($interval / self::ENERGY_REFILL_INTERVAL); //incement energy every 5 minutes

        $refillSum = $refillMultiplier * $this->refillPerInterval;
        if ($refillSum > $refillable) {
            $refillSum = $refillable;
        }

        if ($refillSum < 1) {
            return false; //don't need to rest
        }

        $this->energy += $refillSum;

        $remain = 0;
        if ($interval <= self::ENERGY_REFILL_INTERVAL * 5) {
            $remain = $interval - ($refillMultiplier * self::ENERGY_REFILL_INTERVAL);
        }

        $this->energy_incr_at = date("Y-m-d H:i:s", $now-$remain);

        Yii::app()->db->createCommand()
            ->update('main', ['energy'=>$this->energy, 'energy_incr_at'=>$this->energy_incr_at], 'uid=:uid', [':uid'=>(int)$this->uid]);
    }

    public function updateAttributes($toIncrement, $toDecrement)
    {
        $this->logEnergyUsage($toDecrement);
        $attributes = [];

        $toIncrement = $this->incrementLevel($toIncrement);

        foreach ($toIncrement as $k => $v) {
            $newValue = $this->$k + $v;
            $attributes[$k] = $newValue;
            $this->$k = $newValue;

            if ($k=='dollar') {
                (new ProfileBadgeActivator())->triggerDollar($this->uid, $newValue);
            }
        }

        //level advance, reset energy
        if (isset($attributes['level'])) {
            unset($toDecrement['energy']);
            Yii::app()->gameLogger->log(['type'=>'level_up']);
        }

        foreach ($toDecrement as $k => $v) {
            if ($v > $this->$k) {
                $v = $this->$k;
            }

            $newValue = $this->$k - $v;
            $attributes[$k] = $newValue;
            $this->$k = $newValue;
        }


        if (!empty($attributes)) {
            Yii::app()->db->createCommand()
            ->update('main', $attributes, 'uid=:uid', [':uid'=>(int)$this->uid]);
        }
    }

    protected function logEnergyUsage($attributes)
    {
        if (!isset($attributes['energy'])) {
            return false;
        }

        //todo: implement redis log
        $used = $attributes['energy'];

controllers/PlayerController.php
<?php
class PlayerController extends GameController
{
    public $defaultAction = 'profile';

    public function actionProfile($uid = 0)
    {
        $player = Yii::app()->player->model;
        $playerStats = new PlayerStats;
        $playerStats->uid = $player->uid;

        //other player
        if ($uid) {
            $player = new Player;
            $player->setAllAttributes($uid);
            $playerStats->uid = $uid;

            if (!$player->uid) {
                throw new CHttpException(404, 'A keresett felhasználó nem található.');
            }
            
            $duelShiel = new DuelShield();
            $duelShiel->uid = $uid;
            if ($duelShiel->lifeTime > 0) {
                $player->activateDuelShield();
            }
        }

        $advancement = $this->advancement($player);

        //stats
        $playerStats->fetchStats();

        //badges
        $badgeList = new BadgeList;
        $badgeList->uid = $uid;
        $badgeList->fetchOwned();

        $this->render('profile', [
            'player' => $player,
            'playerStats' => $playerStats,
            'badgeList' => $badgeList,
            'advancement' => $advancement
            ]);
    }

    public function actionBadges()
    {
        $badgeList = new BadgeList;
        $badgeList->fetchOwned();
        $badgeList->fetchAll();

        $this->render('badges', [
            'badgeList' => $badgeList
            ]);
    }

    protected function advancement($player)
    {
        $advancement = null;
        if ($player->status_points) {
            $advancement = new Advancement;
            $advancement->uid = $player->uid;

            $increment_id = Yii::app()->request->getPost('increment_id', 0);
            if ($increment_id) {
                $advancement->incrementForStatuspoint($increment_id);
            }
        }

        return $advancement;
    }
}

views/player/_badges_own.php
<div class="nav">
    <?= CHtml::link('összes érme', ['player/badges'], ['data-role'=>'button', 'data-inline'=>'true', 'data-mini'=>'true', 'class'=>'right']); ?>
    <h3>Legújabb érméim</h3>
</div>
<div class="prog-bar">
    <div class="ui-slider-track ui-btn-down-e ui-btn-corner-all">
        <div class="ui-slider-bg ui-btn-active ui-btn-corner-all" style="width: <?= $badgeList->percentOwned; ?>%;"></div>
        <p class="desc">megszerzett érmék: <?= $badgeList->percentOwned; ?>%</p>
    </div>
</div>

<div class="badges badges-last">
<?php
$i = 1;
foreach ($badgeList->owned as $k => $v): ?>
    <p><span class="badge badge-<?= $v['level']; ?>"></span><?= isset($v['body']) ? $v['body'] : '...'; ?></p>
<?php 
    if ($i >= 5) break;
    $i++;
endforeach; 
?>
</div>

views/player/badges.php
<?php
$this->pageTitle='Összes érme';
?>

<div class="nav">
    <?= CHtml::link('profilom', ['/player'], ['data-role'=>'button', 'data-inline'=>'true', 'data-mini'=>'true', 'class'=>'right']); ?>
    <h1>Összes érme</h1>
</div>

<div class="coll-badges" data-role="collapsible-set" data-theme="c" data-content-theme="d">
    <div class="badges" data-role="collapsible" data-collapsed="false">
        <h3>Bronz</h3>
        <?php foreach ($badgeList->all['b'] as $k => $v): ?>
            <p>
            <span class="badge badge-<?= $v['level']; ?><?= $v['owned']?'':'x'; ?>"></span>
            <?= isset($v['body']) ? $v['body'] : '...'; ?>
            </p>
        <?php endforeach; ?>
    </div>
    <div class="badges" data-role="collapsible">
        <h3>Ezüst</h3>
        <?php foreach ($badgeList->all['s'] as $k => $v): ?>
            <p>
            <span class="badge badge-<?= $v['level']; ?><?= $v['owned']?'':'x'; ?>"></span>
            <?= isset($v['body']) ? $v['body'] : '...'; ?>
            </p>
        <?php endforeach; ?>
    </div>
    <div class="badges" data-role="collapsible">
        <h3>Arany</h3>
        <?php foreach ($badgeList->all['g'] as $k => $v): ?>
            <p>
            <span class="badge badge-<?= $v['level']; ?><?= $v['owned']?'':'x'; ?>"></span>
            <?= isset($v['body']) ? $v['body'] : '...'; ?>
            </p>
        <?php endforeach; ?>
    </div>
</div>

views/player/profile.php
<?php
$this->pageTitle='Adatlap: ' . $player->user;
?>
<div class="nav">
    <div class="right">
        <div data-role="controlgroup" data-type="horizontal" data-mini="true">
        <?php
        if ($player->itsMe()) {
            echo CHtml::link('e-mail', ['/setup/email'], ['data-role'=>'button', 'data-inline'=>'true', 'data-mini'=>'true']);
            echo CHtml::link('jelszó', ['/setup/password'], ['data-role'=>'button', 'data-inline'=>'true', 'data-mini'=>'true']);
        } else {
            $cssClass = '';
            if ($player->level < Yii::app()->params['duelLevelRequirement']) $cssClass .= ' ui-disabled';
            echo CHtml::link('párbajra hívom', ['duel/go', 'opponentId'=>$player->uid], ['data-role'=>'button', 'data-inline'=>'true', 'data-mini'=>'true', 'class'=>$cssClass]);
        }
        ?>
        </div>
    </div>
    <h1>játékos: <?= $player->user ?></h1>
</div>

<?php if ($player->status_points): ?>
<ul id="statuspoints" data-role="listview" data-inset="true">
    <li>
        <p><strong class="success">Fejlődtél!</strong> A státuszpontjaid felhasználásával megnövelheted az itt látható tulajdonságaidat vagy pénzedet.</p>
        <form action="<?= $this->createUrl(''); ?>" method="post">
            <div data-role="controlgroup" data-type="horizontal" data-mini="true">
                <button name="increment_id" value="1">+1 max. energia</button>
                <button name="increment_id" value="2">+<?= $advancement->skillImprovement ?> szakértelem</button>
                <button name="increment_id" value="3">+2 teherbírás</button>
                <button name="increment_id" value="4">+<?= $advancement->dollarImprovement ?>$</button>
            </div>
        </form>
        <p class="sp">Státuszpontok: <span><?= $player->status_points ?></span></p>
    </li>
</ul>
<?php endif; ?>

<div class="responsive-a info ui-grid-a">
    <div class="ui-block-a">
        <table class="table-stripe strong">
            <tbody>
            <tr><td>szint</td><td><?= $player->level ?></td></tr>
            <?php if ($player->itsMe()): ?>
            <tr><td>max energia</td><td><?= $player->energy_max ?></td></tr>
            <?php else: ?>
            <tr><td>energia/max</td><td><?= $player->energy . '/' . $player->energy_max ?></td></tr>
            <?php endif; ?>
            <tr><td>pénz</td><td><?= $player->dollar ?>$</td></tr>
            <tr><td>teherbírás</td><td><?= $player->strength ?></td></tr>
            <tr><td>alap szakértelem</td><td><?= $player->skill ?></td></tr>
            <tr><td>teljes szakértelem</td><td><?= $player->skill_extended ?></td></tr>
            </tbody>
        </table>


        <h2>Részletek</h2>
        <table class="table-stripe">
            <tbody>
            <tr>
                <td>teljesített küldetések</td>
                <td><?= $playerStats->stats['completed_missions'] ?></td>
            </tr>
            <tr>
                <td>meglátogatott vizek</td>
                <td><?= $playerStats->stats['visited_waters'] ?></td>
            </tr>
            <tr>
                <td>meglátogatott megyék</td>
                <td><?= $playerStats->stats['visited_counties'] ?></td>
            </tr>
            <tr>
                <td>megnyert párbajok</td>
                <td><?= $playerStats->stats['duel_success'] ?></td>
            </tr>
            <tr>
                <td>elveszített párbajok</td>
                <td><?= $playerStats->stats['duel_fail'] ?></td>
            </tr>
            <tr>
                <td>párbajsikerek aránya</td>
                <td><?= $playerStats->stats['duel_rate'] ?>%</td>
            </tr>
            <tr>
                <td>felszerelések</td>
                <td><?= $player->owned_items ?></td>
            </tr>
            <tr>
                <td>csalik</td>
                <td><?= $player->owned_baits ?></td>
            </tr>
            <tr>
                <td>szettek</td>
                <td><?= $playerStats->stats['owned_setitems'] ?></td>
            </tr>
            <tr>
                <td>aktuális rang</td>
                <td><?= $playerStats->stats['rankActual']?'#'.$playerStats->stats['rankActual']:'-' ?></td>
            </tr>
            <tr>
                <td>összesített rang</td>
                <td><?= $playerStats->stats['rank']?'#'.$playerStats->stats['rank']:'-' ?></td>
            </tr>
            <tr>
                <td>klub</td>
                <td><?= $player->in_club ? CHtml::link($player->clubName, ['club/details', 'id'=>$player->in_club]) : '-'; ?></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="gear ui-block-b">

        <ul data-role="listview" data-inset="true">
            <li data-role="list-divider">3 legjobb felszerelés</li>
            <?php foreach ($playerStats->stats['items'] as $i): ?>
            <li><?= $i ?></li>
            <?php endforeach; ?>
            <li data-role="list-divider">3 legjobb csali</li>
            <?php foreach ($playerStats->stats['baits'] as $i): ?>
            <li><?= $i ?></li>
            <?php endforeach; ?>
            <li data-role="list-divider">3 legjobb szett</li>
            <?php foreach ($playerStats->stats['sets'] as $i): ?>
            <li><?= $i ?></li>
            <?php endforeach; ?>
        </ul>

    </div>
</div><!-- /grid-a -->

<?php if ($player->itsMe()) $this->renderPartial('_badges_own', ['badgeList'=>$badgeList]); ?>

<?php $this->widget('HelpWidget', ['topic'=>'profile']); ?>